version: '3.8'

services:
  airflow:
    image: apache/airflow:2.8.0-python3.11
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=mlops-secret-key
    volumes:
      - ../dags:/opt/airflow/dags
      - ../src:/opt/airflow/src
      - airflow-logs:/opt/airflow/logs
    ports:
      -  "8081:8080"
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true && airflow standalone"

volumes:
  airflow-logs: